site: Jonathan Copeland

url: jcopeland.co
title: Jonathan Copeland
subtitle: Helping people feel smarter in their day-to-day lives
author: Jonathan Copeland
description:

baseurl: /

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /notes/:slug
  # projects:
  #   output: true
  #   permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 6
paginate_path: "/notes/page:num/"
  