basic_settings:
  site_title: Jonathan Copeland
  site_tagline: Helping people feel smarter in their day-to-day lives
  favicon_image: /images/favicon.ico

header_settings:
  avatar_image: /images/profileLight.png
  logo_image: 
  logo_width: 200
  back_icon: /images/back.svg

menu_settings:
  menu_items:
    - title: 'Blog'
      url: '/'
    - title: 'About'
      url: '/about.html'

grid_settings:
  grid_spacing: 10

light_color_settings:
  background_color: '#F3F2F1'
  background_dark_color: '#EFEFEF'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#323130'
  text_light_color: '#ABB7B7'
  accent_color: '#0F6CBD'
  border_color: '#f7d7b6'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'
  card_color: '#FFF'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">'
  title_font: '"Inter", sans-serif'
  body_font: '"Inter", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 27
    medium_size: 32
    large_size: 40
    weight: 600
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 27
    medium_size: 38
    large_size: 40
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 24
    medium_size: 28
    large_size: 32
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 17
    medium_size: 19
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 21
    medium_size: 23
    large_size: 24
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  custom_styles: ""
  header_js: ""
  footer_js: ""